<?php

/**
 * List All Live Events
 * For Post /event/Event/Create
 */
$this->headScript()
    ->prependFile($this->basePath('/zf2/assets/event/hangout/index/indexServices.js'))
    ->appendFile($this->basePath('/zf2/assets/event/js/event/myLiveEventSelectCtrl.js'));
$this->headLink()
    ->prependStylesheet($this->basePath('/zf2/assets/event/css/selectEvent.css'));


?>

<div ng-app="eventPlanner">
    <div ng-controller="myLiveEventSelectCtrl">
        <div class="modal fade hmodal-success" id="myModal11" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body modalTest2">
                        <configure-gh-1 ng-if="templateToDisplay === 'configureGHStep1'" class="modalContentBox2 animateFade" cancel="cancel" next="next" modal-content="modalContent"></configure-gh-1>
                        <configure-gh-2 ng-if="templateToDisplay === 'configureGHStep2'" class="modalContentBox2 animateFade" cancel="cancel" hangout="hangout" modal-content="modalContent" next="next" previous="previous" submit="submit"></configure-gh-2>
                    </div>
                </div>
            </div>
        </div>

        <div class="page greyBackground">
            <div class="eventHeader">
                <h2 class="blackText">My Live Events</h2>
                <p>Select from the Live Events below to create your Virtual Event, edit the live event, or delete the live event.</p>
            </div>
            <br/>
            <div class="contentContainer">
                <div class="row">
                    <div id="{{'event' + $index}}" class="col-xs-12 col-sm-6 event" ng-repeat="event in events">
                        <div class="hpanel hgreen">
                            <div class="panel-body">
                                <div class="row marginBottomFifteen">
                                    <div class="col-md-7">
                                        <div class="eventName">
                                            {{event.name}}
                                        </div>
                                        <div class="eventDateTopic">
                                            <div class="row marginBottomFive">
                                                <div class="col-sm-6 col-md-7">
                                                    <div class="eventSelectSmallHeader">
                                                        DATE
                                                    </div>
                                                    <div class="eventSelectSmallText">
                                                        {{event.start | date: 'shortDate'}}
                                                    </div>
                                                </div>
                                                <div class="col-sm-6 col-md-5">
                                                    <div class="eventSelectSmallHeader">
                                                        TIME
                                                    </div>
                                                    <div class="eventSelectSmallText">
                                                        {{event.start | date: 'shortTime'}}
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="eventSelectSmallHeader">
                                                        TOPIC
                                                    </div>
                                                    <div class="eventSelectSmallText">
                                                        {{event.topic}}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <div id="{{'eventHostHolder' + $index}}" class="eventHostsHolder">
                                            <div class="eventHost" ng-repeat="host in event.host">
                                                <div class="hostImage">
                                                    <img class="contentImg" src="{{host.imageUrl}}" alt="" />
                                                </div>
                                                <div class="hostName marginTopTen">
                                                    {{host.name}}
                                                </div>
                                                <div class="hostRoles eventSelectSmallText">
                                                    Presentor
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="eventButtons">
                                            <div class="row marginBottomFive">
                                                <div class="col-sm-12">
                                                    <button ng-if="event.configureGH" class="btn brand-button-success eventSelectButton marginTopFive" ng-click="configureGoogleHangout(event.id)">Configure Google Hangouts</button>
                                                    <button ng-if="!event.configureGH" ng-disabled="!event.startable" class="btn brand-button-success eventSelectButton marginTopFive" ng-click="startEvent(event, $index)">Start Live Event</button>
                                                    <button class="btn brand-button-warn btn-outline eventSelectButton marginTopFive" ng-click="editLiveEvent(event, $index)"><i class="fa fa-clipboard" aria-hidden="true"></i>&nbsp;Edit</button>
                                                    <button ng-if="!event.hasChildren" class="btn brand-button-fail btn-outline eventSelectButton marginTopFive" ng-click="deleteLiveEvent(event, $index)"><i class="fa fa-trash-o" aria-hidden="true"></i>&nbsp;Delete</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div id="blank" class="col-xs-12 col-sm-6 event">
                        <div class="hpanel hgreen">
                            <div class="panel-body">
                                <div class="row marginBottomFifteen">
                                    <div class="col-md-7">
                                        <div class="eventName">
                                            Create New Live Event
                                        </div>
                                        <div class="eventDateTopic">
                                            <div class="row marginBottomFive">
                                                <div class="col-sm-6 col-md-7">
                                                    <div class="eventSelectSmallHeader">
                                                        DATE
                                                    </div>
                                                    <div class="eventSelectSmallText">
                                                    </div>
                                                </div>
                                                <div class="col-sm-6 col-md-5">
                                                    <div class="eventSelectSmallHeader">
                                                        TIME
                                                    </div>
                                                    <div class="eventSelectSmallText">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="eventSelectSmallHeader">
                                                        TOPIC
                                                    </div>
                                                    <div class="eventSelectSmallText">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="eventHostsHolder">
                                            <div class="eventHost">
                                                <div class="blankHostImage">
                                                    <img src="/zf2/assets/event/images/greyPicHolder.png" alt="" />
                                                </div>
                                                <div class="hostRoles eventSelectSmallText">
                                                    Presentor
                                                </div>
                                            </div>
                                            <div class="eventHost">
                                                <div class="blankHostImage">
                                                    <img src="/zf2/assets/event/images/greyPicHolder.png" alt="" />
                                                </div>
                                                <div class="hostRoles eventSelectSmallText">
                                                    Presentor
                                                </div>
                                            </div>
                                            <div class="eventHost">
                                                <div class="blankHostImage">
                                                    <img src="/zf2/assets/event/images/greyPicHolder.png" alt="" />
                                                </div>
                                                <div class="hostRoles eventSelectSmallText">
                                                    Presentor
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="eventButtons">
                                            <div class="row marginBottomFive">
                                                <div class="col-sm-12">
                                                    <button class="btn brand-button-success" ng-click="createLiveEvent()">Create New Live Event</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- To Detect Bootstrap Breakpoints -->
<div class="device-xs visible-xs"></div>
<div class="device-sm visible-sm"></div>
<div class="device-md visible-md"></div>
<div class="device-lg visible-lg"></div>
<!-- -->