<?php
    $this->headScript()
        ->appendFile($this->basePath('/zf2/assets/event/js/event/eventCreateCtrl.js'))
        ->appendFile($this->basePath('/zf2/assets/event/js/event/videoSvc.js'))
        ->appendFile($this->basePath('/js/facebook/PlatformAuthentication.js'))
        ->appendFile($this->basePath('/zf2/assets/event/js/event/touch-punch.min.js'));
    $this->headLink()
        ->prependStylesheet($this->basePath('/zf2/assets/event/css/createEvent.css'));
    echo '<script>';
    echo 'var fbUserId = ' . $this->facebookUid . ';';
    echo '</script>';
?>
<div ng-app="eventPlanner">
    <div ng-controller="eventCreateCtrl">

        <div class="modal fade hmodal-success" id="myModal9" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body modalTest2">
                        <wizard-modal
                            available-fb-events="availableFbEvents"
                            available-fb-groups="availableFbGroups"
                            cancel="cancel"
                            create-facebook-event="createFacebookEvent"
                            create-facebook-group="createFacebookGroup"
                            event="event"
                            modal-content="modalContent"
                            next="next"
                            previous="previous"
                            save-Fb-Groups-Events="saveFbGroupsEvents"
                            template-to-display="templateToDisplay"
                            validate-event="validateEvent"
                            validate-group="validateGroup">
                        </wizard-modal>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade hmodal-success" id="myModal10" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body modalTest" >
                        <div class="modalContentBox">
                            <form action="">
                                <h3>Add Comment</h3>
                                <textarea class="form-control" type="text" ng-model="postToEdit.comment" placeholder="Enter Comment Here..." required></textarea>
                                <br/>
                                <div class="postTimeSelectors">
                                    <div ng-click="changePostTime('now')">
                                        <div class="cursorPointer">
                                            NOW
                                            <br/>
                                            <div ng-show="postTime === 'now'" class="postTimeSelectorUnderline">&nbsp;NOW&nbsp;</div>
                                        </div>
                                    </div>
                                    <div ng-click="changePostTime('later')">
                                        <div class="cursorPointer">
                                            LATER
                                            <br/>
                                            <div ng-show="postTime === 'later'" class="postTimeSelectorUnderline">&nbsp;LATER&nbsp;</div>
                                        </div>
                                    </div>
                                    <div ng-click="changePostTime('optimize')">
                                        <div class="cursorPointer">
                                            OPTIMIZE
                                            <br/>
                                            <div ng-show="postTime === 'optimize'" class="postTimeSelectorUnderline">&nbsp;OPTIMIZE&nbsp;</div>
                                        </div>
                                    </div>
                                </div>
                                <div ng-show="postTime === 'later'" class="animate-show-expand">
                                    <div class="input-group" id="datepickerHolder1">
                                        <input id="datepicker1" type="text" class="form-control greyBackground" ng-model="postToEdit.date"/>
                                        <div class="input-group-addon btn greyBackground" ng-click="showDatepicker1()">
                                            <span class="glyphicon glyphicon-th"></span>
                                        </div>
                                    </div>
                                    <div class="input-group bootstrap-timepicker timepicker">
                                        <input id="timepicker1" type="text" class="form-control input-small greyBackground" ng-model="postToEdit.time"/>
                                        <div class="input-group-addon btn greyBackground" ng-click="showTimepicker1()" >
                                            <i class="glyphicon glyphicon-time"></i>
                                        </div>
                                    </div>
                                    <select ng-options="item.value for item in availableTimeZones track by item.value" ng-model="postToEdit.timeZone" class="form-control input-small greyBackground">
                                        <option value="" disabled selected>Select Time Zone</option>
                                    </select>
                                    <br/>
                                </div>
                            </form>
                            <br/>
                            <h4>Comment Ideas:</h4>
                            {{postToEdit.suggestedText}}
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button ng-click="submitPost()" class="btn brand-button-success">Submit</button>
                        <button class="btn btn-outline brand-button-warn" data-dismiss="modal" ng-click="postTime = 'now'">Cancel</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade hmodal-success" id="myModal11" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body modalTest" >
                        <div class="modalContentBox">
                            <form action="">
                                <h3>Add Comment</h3>
                                <textarea class="form-control" type="text" ng-model="postToEdit.comment" placeholder="Enter Comment Here..." required></textarea>
                                <br/>
                                <div class="postTimeSelectors">
                                    <div ng-click="changePostTime('now')">
                                        <div class="cursorPointer">
                                            NOW
                                            <br/>
                                            <div ng-show="postTime === 'now'" class="postTimeSelectorUnderline">&nbsp;NOW&nbsp;</div>
                                        </div>
                                    </div>
                                    <div ng-click="changePostTime('later')">
                                        <div class="cursorPointer">
                                            LATER
                                            <br/>
                                            <div ng-show="postTime === 'later'" class="postTimeSelectorUnderline">&nbsp;LATER&nbsp;</div>
                                        </div>
                                    </div>
                                    <div ng-click="changePostTime('optimize')">
                                        <div class="cursorPointer">
                                            OPTIMIZE
                                            <br/>
                                            <div ng-show="postTime === 'optimize'" class="postTimeSelectorUnderline">&nbsp;OPTIMIZE&nbsp;</div>
                                        </div>
                                    </div>
                                </div>
                                <div ng-show="postTime === 'later'" class="animate-show-expand">
                                    <div class="input-group" id="datepickerHolder2">
                                        <input id="datepicker2" type="text" class="form-control greyBackground" ng-model="postToEdit.date">
                                        <div class="input-group-addon btn greyBackground" ng-click="showDatepicker2()">
                                            <span class="glyphicon glyphicon-th"></span>
                                        </div>
                                    </div>
                                    <div class="input-group bootstrap-timepicker timepicker">
                                        <input id="timepicker2" type="text" class="form-control input-small greyBackground" ng-model="postToEdit.time"/>
                                        <div class="input-group-addon btn greyBackground" ng-click="showTimepicker2()" >
                                            <i class="glyphicon glyphicon-time"></i>
                                        </div>
                                    </div>
                                    <select ng-options="item.value for item in availableTimeZones track by item.value" ng-model="postToEdit.timeZone" class="form-control input-small greyBackground"></select>
                                    <br/>
                                </div>
                            </form>
                            <br/>
                            <h4>Comment Ideas:</h4>
                            {{postToEdit.suggestedText}}
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button ng-click="submitEditedPost()" class="btn brand-button-success">Submit</button>
                        <button class="btn btn-outline brand-button-warn" data-dismiss="modal" ng-click="postTime = 'now'">Cancel</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="page greyBackground">
            <div class="eventHeader">
                <h2 class="blackText">Virtual Event Manager</h2>
                <p>Schedule posts and manage connected Facebook groups and Facebook events.</p>
            </div>
            <div class="contentContainer">
                <div class="row">
                    <div class="col-md-6">
                        <div class="hpanel">
                            <div class="panel-heading">
                                <div class="panel-tools">
                                    <a class="showhide"><i class="fa fa-chevron-up"></i></a>
                                </div>
                                Event overview
                            </div>
                            <div class="panel-body paddingAllOverride">
                                <div class="eventOverviewPanel">
                                    <div class="eventOverviewPanel1">
                                        <img src="/StaticContent/Event/img/event_overview.jpg" alt="" class="eventImg">
                                    </div>
                                    <div class="eventOverviewPanel2">
                                        <div class="eventName">{{event.name}}</div>
                                        <div class="eventDate">{{event.start | date: 'longDate'}} | {{event.start | date: 'shortTime'}}</div>
                                        <div class="eventHostsHeader">Event Host<span ng-show="event.host.length > 1">s</span></div>
                                        <div class="eventHosts">{{event.hosts}}</div>
                                        <div class="eventUrlHeader">
                                            Event URL
                                        </div>
                                        <a href="{{event.short_url}}" target="_blank">
                                            <div class="eventUrl">
                                                {{event.short_url}}
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="hpanel hgreen">
                            <div class="panel-heading">
                                <div class="panel-tools">
                                    <a href=""><i class="fa fa-plus" ng-click="getFbPermission('', false)"></i></a>
                                    <a class="showhide"><i class="fa fa-chevron-up"></i></a>
                                </div>
                                Facebook Group/Event Management
                            </div>
                            <div ng-show="(!event.facebookGroups || event.facebookGroups.length === 0) && (!event.facebookEvents || event.facebookEvents.length === 0)" class="panel-body">
                                <div class="row">
                                    <div class="col-sm-12">
                                        No groups or events
                                    </div>
                                </div>
                            </div>

                            <div class="panel-body marginBottomFive" ng-repeat="group in event.facebookGroups">
                                <div class="row">
                                    <div class="col-xs-5">
                                        {{group.name}}
                                    </div>
                                    <div class="col-xs-7">
                                        <div class="eventGroupInfo">
                                            <div class="eventGroupInfo1">
                                                <button class="btn brand-button-success" ng-click="validateGroup('createGroupInstructions', 'createGroupInstructions', group.id)">EDIT</button>
                                            </div>
                                            <div ng-show="group.progress" class="eventGroupInfo2">
                                                <div>{{group.progress}}% complete</div>
                                                <div class="progress full progress-small">
                                                    <div id="{{'groupProgressBar' + $index}}" aria-valuemax="100" aria-valuemin="0" role="progressbar" class=" progress-bar progress-bar-success">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="panel-body marginBottomFive" ng-repeat="event in event.facebookEvents">
                                <div class="row">
                                    <div class="col-xs-5">
                                        {{event.name}}
                                    </div>
                                    <div class="col-xs-7">
                                        <div class="eventGroupInfo">
                                            <div class="eventGroupInfo1">
                                                <button class="btn brand-button-success" ng-click="validateEvent('createEventInstructions', 'createEventInstructions', event.id)">EDIT</button>
                                            </div>
                                            <div ng-show="event.progress" class="eventGroupInfo2">
                                                <div>{{event.progress}}% complete</div>
                                                <div class="progress full progress-small">
                                                    <div id="{{'eventProgressBar' + $index}}" aria-valuemax="100" aria-valuemin="0" role="progressbar" class=" progress-bar progress-bar-success">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="hpanel">
                            <div class="panel-heading">
                                Project participants
                            </div>
                            <div class="row">
                                <div ng-show="event.attendees.length === 0" class="col-sm-12">
                                    <div class="hpanel">
                                        <div class="panel-body">
                                            {{event.loadingEventAttendees}}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-4" ng-repeat="attendee in event.attendees">
                                    <div class="hpanel">
                                        <div class="panel-body">
                                            <div class="attendeeImgHolder">
                                                <div class="attendeeImg">
                                                    <img src="{{attendee.url}}" alt=""/>
                                                </div>
                                            </div>
                                            <div class="attendeeName">{{attendee.name}}</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="hpanel">
                            <div class="panel-heading">
                                <div class="panel-tools">
                                    <a class="showhide"><i class="fa fa-chevron-up"></i></a>
                                </div>
                                Posts
                            </div>
                            <div class="panel-body postBody">
                                <ul class="nav nav-tabs">
                                    <li id="scheduledPosts" class="active postTabs" ng-click="getScheduledPosts()"><a data-toggle="tab" href="#tab-1">Scheduled</a></li>
                                    <li id="availablePosts" class="postTabs"><a data-toggle="tab" href="#tab-2">Available</a></li>
                                    <li id="previousPosts" class="postTabs" ng-click="getPreviousPosts()"><a data-toggle="tab" href="#tab-3">Previous</a></li>
                                </ul>
                                <div class="tab-content">
                                    <div id="tab-1" class="tab-pane active">
                                        <div class="panel-body">
                                            <div class="v-timeline vertical-container animate-panel"  data-child="vertical-timeline-block" data-delay="1">
                                                <div ng-show="scheduledPostedPosts.length === 0" class="vertical-timeline-block">
                                                    <div class="vertical-timeline-icon navy-bg">
                                                        <i class="fa fa-calendar"></i>
                                                    </div>
                                                    <div class="vertical-timeline-content">
                                                        <div class="p-sm">
                                                            No scheduled posts
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="vertical-timeline-block" ng-repeat="scheduledPost in scheduledPostedPosts track by $index">
                                                    <div class="vertical-timeline-icon navy-bg  icon-dot-holder" ng-click="editPost(scheduledPost)">
                                                        <div class="icon-dot2"></div>
                                                        <i class="fa fa-calendar icon-calendar"></i>
                                                    </div>
                                                    <div class="vertical-timeline-content">
                                                        <div class="postHolderOutside">
                                                            <div class="postComment">{{scheduledPost.comment}}</div>
                                                            <div class="postHolder">
                                                                <div class="removeBtnHolder">
                                                                  <i class="fa fa-times-circle removeBtn" ng-click="removeScheduledPost(scheduledPost)"></i>
                                                                </div>
                                                                <div class="postImgHolder">
                                                                    <img src="{{scheduledPost.url}}" alt="" class="postImg">
                                                                </div>
                                                                <div class="postInformation">
                                                                    <div class="prodInformationInside">
                                                                        <div class="postTitle">{{scheduledPost.title}}</div>
                                                                        <div class="postDesc">{{scheduledPost.message}}</div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="panel-footer">
                                                            {{scheduledPost.displayDate}}
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div id="tab-2" class="tab-pane">
                                        <div class="panel-body">
                                            <div class="v-timeline vertical-container animate-panel"  data-child="vertical-timeline-block" data-delay="1">
                                                <div ng-show="event.posts.length === 0" class="vertical-timeline-block">
                                                    <div class="vertical-timeline-icon icon-dot-holder">
                                                        <div class="icon-dot-none"></div>
                                                    </div>
                                                    <div class="vertical-timeline-content">
                                                        <div class="p-sm">
                                                            No posts available
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="vertical-timeline-block" ng-repeat="post in event.posts track by $index">
                                                    <div class="vertical-timeline-icon icon-dot-holder" ng-click="schedulePost(post)">
                                                        <div class="icon-dot"></div>
                                                        <i class="fa fa-check icon-checkmark" aria-hidden="true"></i>
                                                    </div>
                                                    <div class="vertical-timeline-content">
                                                        <div class="postHolderOutside">
                                                            <div class="postHolder">
                                                                <div class="postImgHolder">
                                                                  <img src="{{post.url}}" alt="" class="postImg">
                                                                </div>
                                                                <div class="postInformation">
                                                                    <div class="prodInformationInside">
                                                                        <div class="postTitle">{{post.title}}</div>
                                                                        <div class="postDesc">{{post.message}}</div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div id="tab-3" class="tab-pane">
                                        <div class="panel-body">
                                            <div class="v-timeline vertical-container animate-panel"  data-child="vertical-timeline-block" data-delay="1">
                                                <div ng-show="previousPosts.length === 0" class="vertical-timeline-block">
                                                    <div class="vertical-timeline-icon navy-bg">
                                                        <i class="fa fa-calendar"></i>
                                                    </div>
                                                    <div class="vertical-timeline-content">
                                                        <div class="p-sm">
                                                            No previously posted posts
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="vertical-timeline-block" ng-repeat="previousPost in previousPosts track by $index">
                                                    <div class="vertical-timeline-icon navy-bg">
                                                        <i class="fa fa-calendar"></i>
                                                    </div>
                                                    <div class="vertical-timeline-content">
                                                        <div class="postHolderOutside">
                                                            <div class="postComment">{{previousPost.comment}}</div>
                                                            <div class="postHolder">
                                                                <div class="postImgHolder">
                                                                    <img src="{{previousPost.url}}" alt="" class="postImg">
                                                                </div>
                                                                <div class="postInformation">
                                                                    <div class="prodInformationInside">
                                                                        <div class="postTitle">{{previousPost.title}}</div>
                                                                        <div class="postDesc">{{previousPost.message}}</div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="panel-footer">
                                                            {{previousPost.displayDate}}
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="contentFooter-fixed">
                    <button class="btn brand-button-success" ng-click="saveEvent()">Save Event</button>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- To Detect Bootstrap Breakpoints -->
<div class="device-xs visible-xs"></div>
<div class="device-sm visible-sm"></div>
<div class="device-md visible-md"></div>
<div class="device-lg visible-lg"></div>

<script type="text/javascript" src="https://connect.facebook.net/en_US/sdk.js"></script>