<?php
$this->headScript()
    ->appendFile($this->basePath('/zf2/assets/event/js/event/myEventSelectCtrl.js'))
    ->appendFile($this->basePath('/zf2/assets/event/js/event/clipboard.min.js'));
$this->headLink()
    ->prependStylesheet($this->basePath('/zf2/assets/event/css/selectEvent.css'));

?>
<div ng-app="eventPlanner">
    <div ng-controller="myEventSelectCtrl">

        <div class="modal fade hmodal-success" id="myModal1" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body modalTest" >
                        <div class="modalContentBox">
                            <div class="manageHeader">
                                <h4>Send Invite Instructions:</h4>
                            </div>
                            <div class="videoWrapper">
                                <iframe width="560" height="349" src="{{instructionVideo}}" frameborder="0" allowfullscreen></iframe>
                            </div>
                            <hr/>
                            <div class="instructionText">
                                <ol>
                                    <li class="marginBottomFive">
                                        <div class="marginBottomFive">Copy the following link to your clipboard.</div>
                                        <div class="input-group">
                                            <div class="copyTextToolTip">
                                                <input id="copyThis1" type="text" class="form-control cursorText clipboardText" value="{{eventToShowInModal.liveEvent.short_url}}" ng-click="selectText($event)" readonly>
                                            </div>
                                            <span class="input-group-btn copyTextButtonToolTip">
                                                <button type="button" class="btn btn-default clipboardBtn copyTextSuccess" data-clipboard-target="#copyThis1"><i class="fa fa-file-text-o" aria-hidden="true"></i></button>
                                            </span>
                                        </div>
                                    </li>
                                    <li class="marginBottomFive">
                                        Navigate to where you want to share the link (Facebook, Pinterest, Twitter, etc.).
                                    </li>
                                    <li class="marginBottomFive">
                                        Paste the link you copied (press "control + v" for pc or "command + v" for osx) into the post text area.
                                    </li>
                                    <li>
                                        Submit the post.
                                    </li>
                                </ol>
                            </div>
                            <hr/>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-outline brand-button-warn" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="page greyBackground">
            <div class="eventHeader">
                <h2 class="blackText">My Events</h2>
                <p>Select from the Events below to send invitations to or edit your event.</p>
            </div>
            <br/>
            <div class="contentContainer">
                <div class="row">
                    <div id="{{'event' + $index}}" class="col-xs-12 col-sm-6 event" ng-repeat="event in events">
                        <div class="hpanel hgreen">
                            <div class="panel-body">
                                <div class="row marginBottomFifteen">
                                    <div class="col-md-7">
                                        <div class="eventName">
                                            {{event.name}}
                                        </div>
                                        <div class="eventDateTopic">
                                            <div class="row marginBottomFive">
                                                <div class="col-xs-6 col-sm-6 col-md-7">
                                                    <div class="eventSelectSmallHeader">
                                                        DATE
                                                    </div>
                                                    <div class="eventSelectSmallText">
                                                        {{event.start | date: 'shortDate'}}
                                                    </div>
                                                </div>
                                                <div class="col-xs-6 col-sm-6 col-md-5">
                                                    <div class="eventSelectSmallHeader">
                                                        TIME
                                                    </div>
                                                    <div class="eventSelectSmallText">
                                                        {{event.start | date: 'shortTime'}}
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="eventSelectSmallHeader">
                                                        TOPIC
                                                    </div>
                                                    <div class="eventSelectSmallText">
                                                        {{event.topic}}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <div id="{{'eventHostHolder' + $index}}" class="eventHostsHolder">
                                            <div class="eventHost" ng-repeat="host in event.host">
                                                <div class="hostImage">
                                                    <img class="contentImg" src="{{host.imageUrl}}" alt="" />
                                                </div>
                                                <div class="hostName marginTopTen">
                                                    {{host.name}}
                                                </div>
                                                <div class="hostRoles eventSelectSmallText">
                                                    Presentor
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="eventButtons">
                                            <div class="row marginBottomFive">
                                                <div class="col-sm-12">
                                                    <button class="btn brand-button-success eventSelectButton marginTopFive" ng-click="sendInvites(event, $index)">Send Invites</button>
                                                    <button class="btn brand-button-warn btn-outline eventSelectButton marginTopFive" ng-click="editEvent(event, $index)"><i class="fa fa-clipboard" aria-hidden="true"></i>&nbsp;Edit</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div id="blank" class="col-xs-12 col-sm-6 event">
                        <div class="hpanel hgreen">
                            <div class="panel-body">
                                <div class="row marginBottomFifteen">
                                    <div class="col-md-7">
                                        <div class="eventName">
                                            Create New Event
                                        </div>
                                        <div class="eventDateTopic">
                                            <div class="row marginBottomFive">
                                                <div class="col-xs-6 col-sm-6 col-md-7">
                                                    <div class="eventSelectSmallHeader">
                                                        DATE
                                                    </div>
                                                    <div class="eventSelectSmallText">
                                                    </div>
                                                </div>
                                                <div class="col-xs-6 col-sm-6 col-md-5">
                                                    <div class="eventSelectSmallHeader">
                                                        TIME
                                                    </div>
                                                    <div class="eventSelectSmallText">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="eventSelectSmallHeader">
                                                        TOPIC
                                                    </div>
                                                    <div class="eventSelectSmallText">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="eventHostsHolder">
                                            <div class="eventHost">
                                                <div class="blankHostImage">
                                                    <img src="/zf2/assets/event/images/greyPicHolder.png" alt="" />
                                                </div>
                                                <div class="hostRoles eventSelectSmallText">
                                                    Presentor
                                                </div>
                                            </div>
                                            <div class="eventHost">
                                                <div class="blankHostImage">
                                                    <img src="/zf2/assets/event/images/greyPicHolder.png" alt="" />
                                                </div>
                                                <div class="hostRoles eventSelectSmallText">
                                                    Presentor
                                                </div>
                                            </div>
                                            <div class="eventHost">
                                                <div class="blankHostImage">
                                                    <img src="/zf2/assets/event/images/greyPicHolder.png" alt="" />
                                                </div>
                                                <div class="hostRoles eventSelectSmallText">
                                                    Presentor
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="eventButtons">
                                            <div class="row marginBottomFive">
                                                <div class="col-sm-12">
                                                    <button class="btn brand-button-success eventSelectButton marginTopFive" ng-click="createEvent()">Create New Event</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- To Detect Bootstrap Breakpoints -->
<div class="device-xs visible-xs"></div>
<div class="device-sm visible-sm"></div>
<div class="device-md visible-md"></div>
<div class="device-lg visible-lg"></div>
<!-- -->