<?php
	$this->headScript()
		->prependFile($this->basePath('/zf2/assets/posts/js/video.min.js'))
		->appendFile($this->basePath('/zf2/assets/posts/js/addMediaCtrl.js'));
	$this->headLink()
		->prependStylesheet($this->basePath('/zf2/assets/posts/js/video-js.min.css'))
		->prependStylesheet($this->basePath('/zf2/assets/posts/css/addMedia.css'));
?>
<script type="text/javascript">
	var platformApplications = <?php echo $this->platformApplicationsList; ?>;
	var micThemes = <?php echo $this->micThemes; ?>;
	console.log(micThemes);
</script>
<div class="page3" ng-app="postsApp">
	<div class="postArea" ng-controller="addMediaCtrl">
		<div class="postDefaultsHolder">
			<div class="hpanel">
				<ul class="nav nav-tabs">
					<li class="active"><a data-toggle="tab" href="#createPostTab">Create Post</a></li>
					<li class=""><a data-toggle="tab" href="#createLightboxTab">Create Lightbox</a></li>
				</ul>
				<div class="tab-content">
					<div id="createPostTab" class="tab-pane active">
						<post-management current-media="currentMedia" selected-category="selectedCategory"></post-management>
					</div>
					<div id="createLightboxTab" class="tab-pane">
						<lightbox-management current-media="currentMedia" selected-category="selectedCategory"></lightbox-management>
					</div>
				</div>
			</div>
		</div>

		<div class="mediaLibraryHolder">
			<media-library current-media="currentMedia" selected-category="selectedCategory"></media-library>
		</div>

		<div ng-show="currentMedia.hasOwnProperty('id')" class="currentMediaHolder">
			<div class="currentMedia">
				<h5 class="currentMediaHeader">Currently Selected Media</h5>
				<div class="currentMediaContent">
					<div class="currentMediaTitle">
						{{currentMedia.managementName}}
					</div>
					<div class="currentMediaImageHolder">
						<img src="{{currentMedia.currentMediaImg}}" class="currentMediaImg" alt="No preview available."/>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

