<!-- <h3>Create Template</h3> -->
<?php

    /**
    * List Templates
*
* Post to /LiveEvents/Create
        */
$this->headScript()
    ->appendFile($this->basePath('/js/facebook/PlatformAuthentication.js'))
    ->appendFile($this->basePath('/zf2/assets/event/js/event/templateCreateCtrl.js'))
    ->appendFile($this->basePath('/zf2/assets/event/js/event/videoSvc.js'));
$this->headLink()
    ->prependStylesheet($this->basePath('/zf2/assets/event/css/createTemplate.css'));

?>
<div ng-app="eventPlanner">
    <div ng-controller="templateCreateCtrl">
        <div class="modal fade hmodal-success" id="myModal12" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body modalTest2">
                        <wizard-modal-example template-to-display="templateToDisplay"></wizard-modal-example>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade hmodal-success" id="myModal14" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                     <div class="modal-body modalTest2">
                         <wizard-modal-edit template-to-edit="templateToEdit" save-customizations="saveCustomizations"></wizard-modal-edit>
                     </div>
                </div>
            </div>
        </div>        

        <manage-content-modal
            modal-show="modalShow"
            modal-to-display="modalToDisplay"
            content="content"
            available-posts="postsProducts.posts"
            template-posts="templatePosts"
            available-products="postsProducts.products"
            template-products="templateProducts">
        </manage-content-modal>

        <div class="page greyBackground">
            <form name="saveEventTempalte" ng-submit="submitForm()">
                <div class="eventHeader">
                    <h2 class="blackText">Create Template</h2>
                    <p>Create a Virtual Party template using the options below.</p>
                </div>
                <div class="contentContainer">
                    <div class="hpanel">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="panel-body">
                                    <div class="row paddingBottomTen">
                                        <div class="col-sm-2 rightAlignHolder textAlignRight paddingTopFive">Name</div>
                                        <div class="col-sm-10"><input type="text" ng-model="template.name" class="form-control" placeholder="Enter name here" /></div>
                                    </div>
                                    <div class="row paddingBottomTen">
                                        <div class="col-sm-2 rightAlignHolder textAlignRight paddingTopFive">Description</div>
                                        <div class="col-sm-10"><input type="text" ng-model="template.description" class="form-control" placeholder="Enter a brief description of your event" /></div>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-2 rightAlignHolder textAlignRight">Access</div>
                                        <div class="col-sm-10">
                                            <div class="checkbox checkbox-single brand-checkbox-success checkboxMarginTopOverride">
                                                <input type="checkbox" ng-click="selectAccess('all')" ng-model="accessAll">
                                                <label>Public</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="hpanel">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="panel-body">
                                    <div class="manageHeader">
                                        <h3>Manage Posts</h3>
                                        <h4 class="brand-success-text-color" ng-show="postsProducts.posts.length > 0" data-toggle="modal" data-target="#myModal7" ng-click="showModal('posts')"><i class="fa fa-plus-square cursorPointer" aria-hidden="true"></i></h4>
                                    </div>
                                    <p>The main way of adding content will be by creating new posts and managing how those should be displayed on your web-site. You should create, edit or delete a post via the admin area of Social Suite.</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div ng-show="templatePosts.length === 0" class="postHolder">
                        <div class="row">
                            <div class="col-sm-12 col-md-6 col-lg-4">
                                <div class="hpanel brand-top-line">
                                    <div class="panel-body">
                                        <div class="textAlignCenter">
                                            No posts selected
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="postHolder">
                        <div class="row">
                            <div id="{{'postHolder' + $index}}" class="col-sm-12 col-md-6 col-lg-4" ng-repeat="post in templatePosts track by $index">
                                <div class="hpanel brand-top-line">
                                    <div class="panel-body">
                                        <div>
                                            <img class="contentImg" src="{{post.url}}" alt="">
                                        </div>
                                        <br/>
                                        <div class="row paddingBottomTen">
                                            <div class="col-sm-4 rightAlignHolder paddingTopFive fontWeight600">
                                                Title
                                            </div>
                                            <div class="col-sm-8">
                                                <div class="outlineText">{{post.title}}</div>
                                            </div>
                                        </div>
                                        <div class="row paddingBottomTen">
                                            <div class="col-sm-4 rightAlignHolder paddingTopFive fontWeight600">
                                                Message
                                            </div>
                                            <div class="col-sm-8">
                                                <div class="outlineText">{{post.message}}</div>
                                            </div>
                                        </div>
                                        <div class="row paddingBottomTen">
                                            <div class="col-sm-4 rightAlignHolder paddingTopFive fontWeight600">
                                                Suggested Text
                                            </div>
                                            <div class="col-sm-8">
                                                <div class="outlineText">{{post.suggestedText}}</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="hpanel">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="panel-body">
                                    <div class="manageHeader">
                                        <h3>Manage Products</h3>
                                        <h4 class="brand-success-text-color" ng-show="postsProducts.products.length > 0" data-toggle="modal" data-target="#myModal7" ng-click="showModal('products')"><i class="fa fa-plus-square cursorPointer" aria-hidden="true"></i></h4>
                                    </div>
                                    <p>The main way of adding new products will be by creating new posts and managing how those should be displayed on your web-site. You should create, edit or delete a post via the admin area of Social Suite.</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div ng-show="templateProducts.length === 0" class="postHolder">
                        <div class="row">
                            <div class="col-sm-12 col-md-6 col-lg-4">
                                <div class="hpanel brand-top-line">
                                    <div class="panel-body">
                                        <div class="textAlignCenter">
                                            No products selected
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="productHolder">
                        <div class="row">
                            <div id="{{'productHolder' + $index}}" class="col-sm-12 col-md-6 col-lg-4" ng-repeat="product in templateProducts track by $index">
                                <div class="hpanel brand-top-line">
                                    <div class="panel-body">
                                        <div>
                                            <img class="contentImg" src="{{product.url}}" alt="">
                                        </div>
                                        <br/>
                                        <div class="row paddingBottomTen">
                                            <div class="col-sm-4 rightAlignHolder paddingTopFive fontWeight600">
                                                Name
                                            </div>
                                            <div class="col-sm-8">
                                                <div class="outlineText">{{product.name}}</div>
                                            </div>
                                        </div>
                                        <div class="row paddingBottomTen">
                                            <div class="col-sm-4 rightAlignHolder paddingTopFive fontWeight600">
                                                Description
                                            </div>
                                            <div class="col-sm-8">
                                                <div class="outlineText">{{product.description}}</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="hpanel">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="hpanel">
                                    <ul class="nav nav-tabs">
                                        <li class="active" ng-click="changeModels('group')"><a data-toggle="tab" href="#tab-1">Groups</a></li>
                                        <li class="" ng-click="changeModels('event')"><a data-toggle="tab" href="#tab-2">Events</a></li>
                                    </ul>
                                    <div class="tab-content greyBackground">
                                        <div id="tab-1" class="tab-pane active greyBackground">
                                            <div class="modelOrderContainer greyBackground" ui-sortable="groupSortableOptions" ng-model="list">
                                                <div id="{{'groupModel' + $index}}" class="model" ng-repeat="model in groupModelArray">
                                                    <div>
                                                        Step #{{$index + 1}}
                                                    </div>
                                                    <div id="{{'groupModelHeader' + $index}}" class="modelHeader brand-top-line">
                                                        {{model.modelDataObject.descName}}
                                                    </div>
                                                    <div id="{{'groupModelBody' + $index}}" class="modelBody">
                                                        <p>
                                                            {{model.modelDataObject.descText}}
                                                        </p>
                                                        <div class="hpanel">
                                                            <div class="row">
                                                                <div class="col-xs-6 textAlignCenter">
                                                                    <a ng-if="model.modelDataObject.next !== 'groupEventList'" href="" ng-click="customizeModel(model, 'group', $index)" class="underlineText">Customize</a>
                                                                </div>
                                                                <div class="col-xs-6 textAlignCenter">
                                                                    <a href="" ng-click="viewModelExample(model)" class="underlineText">View Example</a>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div ng-show="model.modelDataObject.fixedPosition">
                                                            <div class="checkbox checkbox-single brand-checkbox-success checkboxMarginTopOverride">
                                                                <input type="checkbox" ng-model="model.required"/>
                                                                <label ng-click="switchCheckbox(model, 'required')">Require</label>
                                                            </div>
                                                        </div>
                                                        <div ng-show="model.modelDataObject.fixedPosition">
                                                            <div class="checkbox checkbox-single brand-checkbox-success checkboxMarginTopOverride">
                                                                <input type="checkbox" ng-model="model.showAnyway"/>
                                                                <label ng-click="switchCheckbox(model, 'showAnyway')">Show Anyway</label>
                                                            </div>
                                                        </div>
                                                        <div ng-show="model.modelDataObject.fixedPosition">
                                                            <div class="checkbox checkbox-single brand-checkbox-success checkboxMarginTopOverride">
                                                                <input type="checkbox" ng-model="model.override"/>
                                                                <label ng-click="switchCheckbox(model, 'override')">Override</label>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="tab-2" class="tab-pane">
                                            <div class="modelOrderContainer greyBackground" ui-sortable="eventSortableOptions" ng-model="list">
                                                <div id="{{'eventModel' + $index}}" class="model" ng-repeat="model in eventModelArray">
                                                    <div>
                                                        Step #{{$index + 1}}
                                                    </div>
                                                    <div id="{{'eventModelHeader' + $index}}" class="modelHeader brand-top-line">
                                                        {{model.modelDataObject.descName}}
                                                    </div>
                                                    <div id="{{'eventModelBody' + $index}}" class="modelBody">
                                                        <p>
                                                            {{model.modelDataObject.descText}}
                                                        </p>
                                                        <div class="hpanel">
                                                            <div class="row">
                                                                <div class="col-xs-6 textAlignCenter">
                                                                    <a ng-if="model.modelDataObject.next !== 'groupEventList'" href="" ng-click="customizeModel(model, 'event', $index)" class="underlineText">Customize</a>
                                                                </div>
                                                                <div class="col-xs-6 textAlignCenter">
                                                                    <a href="" ng-click="viewModelExample(model)" class="underlineText">View Example</a>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div ng-show="model.modelDataObject.fixedPosition">
                                                            <div class="checkbox checkbox-single brand-checkbox-success checkboxMarginTopOverride">
                                                                <input type="checkbox" ng-model="model.required"/>
                                                                <label ng-click="switchCheckbox(model, 'required')">Require</label>
                                                            </div>
                                                        </div>
                                                        <div ng-show="model.modelDataObject.fixedPosition">
                                                            <div class="checkbox checkbox-single brand-checkbox-success checkboxMarginTopOverride">
                                                                <input type="checkbox" ng-model="model.showAnyway"/>
                                                                <label ng-click="switchCheckbox(model, 'showAnyway')">Show Anyway</label>
                                                            </div>
                                                        </div>
                                                        <div ng-show="model.modelDataObject.fixedPosition">
                                                            <div class="checkbox checkbox-single brand-checkbox-success checkboxMarginTopOverride">
                                                                <input type="checkbox" ng-model="model.override"/>
                                                                <label ng-click="switchCheckbox(model, 'override')">Override</label>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- DO NOT REMOVE. NEED AS EXAMPLE. Use this to be able to inject HTML -->
                    <!-- <div ng-bind-html="testData">
                    </div> 

                    This is another way to do it. Pipe it through a filter.
                    <div ng-bind-html="testThisOut | sanitize"></div>
                    $scope.testThisOut = '<h1>Hello World!</h1>'
                    or
                    $scope.testThisOut = 'Hello World!'
                    It doesn't matter;
                    -->
                    <!--          -->

                    <div class="contentFooter-fixed">
                        <button class="btn brand-button-success" type="Submit">Create Template</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- To Detect Bootstrap Breakpoints -->
<div class="device-xs visible-xs"></div>
<div class="device-sm visible-sm"></div>
<div class="device-md visible-md"></div>
<div class="device-lg visible-lg"></div>

<script type="text/javascript" src="https://connect.facebook.net/en_US/sdk.js"></script>