<?php
/**
 * List Templates
 *
 * Post to /LiveEvents/Create
 */
$this->headScript()
    ->appendFile($this->basePath('/zf2/assets/event/js/event/myTemplateSelectCtrl.js'));

$this->headLink()
    ->prependStylesheet($this->basePath('/zf2/assets/event/css/selectTemplate.css'));
?>
<div ng-app="eventPlanner">
    <div ng-controller="myTemplateSelectCtrl">

        <manage-content-modal
            modal-show="modalShow"
            modal-to-display="modalToDisplay"
            content="content"
            available-posts="templatePosts"
            template-posts="templatePosts"
            available-products="templateProducts"
            template-products="templateProducts">
        </manage-content-modal>

        <div ng-show="templates.length === 0" class="page">
            <div class="eventHeader">
                <h3>My Templates</h3>
                <p>Create a template to be able to choose a template to create your Virtual Party, edit the template, or delete the template.</p>
            </div>
            <div class="contentContainer">
                <div class="panel-body">
                    <div class="contentFooter">
                        <button class="btn brand-button-success" ng-click="createNewTemplate()">Create New Template</button>
                    </div>
                    <hr class="underline"/>
                    <div class="eventHeader">No Templates Available</div>
                </div>
            </div>
        </div>

        <div ng-show="templates.length > 0" class="page greyBackground">
            <div class="eventHeader">
                <h2 class="blackText">My Templates</h2>
                <p>Choose from one of the templates below to create your Virtual Party, edit the template, or delete the template.</p>
            </div>
            <div class="contentContainer">
                <div class="panel-body greyBackground">
                    <div class="contentFooter">
                        <button class="btn brand-button-success" ng-click="createNewTemplate()">Create New Template</button>
                    </div>
                    <hr class="underline"/>
                    <div ng-show="templates.length > 0" ng-repeat="template in templates">
                        <div class="hpanel">
                            <div class="panel-body">
                                <div class="templateName">
                                    {{template.translations[0].name}}
                                </div>
                                <p>
                                    {{template.translations[0].description}}
                                </p>
                            </div>
                        </div>

                        <div class="hpanel">
                            <div class="row marginBottomFifteen">
                                <div class="col-sm-12">
                                    <span>Sample Post</span>
                                    <a data-toggle="modal" data-target="#myModal7" ng-click="showModal('posts', $index)" href="">(see all posts)</a>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="postProductContainer">
                                        <div class="postProductImage">
                                            <img class="contentImg" src="{{template.posts[0].url}}" alt="">
                                        </div>
                                        <div class="postProductDescription">
                                            <div class="postProductHeader">
                                                Title
                                            </div>
                                            <div class="postProductInfo">
                                                {{template.posts[0].title}}
                                            </div>
                                            <div class="postProductHeader">
                                                Message
                                            </div>
                                            <div class="postProductInfo">
                                                {{template.posts[0].message}}
                                            </div>
                                            <div class="postProductHeader">
                                                Suggested text
                                            </div>
                                            <div class="postProductInfo">
                                                {{template.posts[0].suggestedText}}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="hpanel">
                            <div class="row marginBottomFifteen">
                                <div class="col-sm-12">
                                    <span>Sample Product</span> 
                                    <a data-toggle="modal" data-target="#myModal7" ng-click="showModal('products', $index)" href="">(see all products)</a>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="postProductContainer">
                                        <div class="postProductImage">
                                            <img class="contentImg" src="{{template.products[0].url}}" alt="">
                                        </div>
                                        <div class="postProductDescription">
                                            <div class="postProductHeader">
                                                Name
                                            </div>
                                            <div class="postProductInfo">
                                                {{template.products[0].name}}
                                            </div>
                                            <div class="postProductHeader">
                                                Description
                                            </div>
                                            <div class="postProductInfo">
                                                {{template.products[0].description}}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="contentFooter">
                            <button class="btn brand-button-success" ng-click="chooseTemplate(template)">Select</button>
                            <button class="btn brand-button-warn btn-outline" ng-click="editTemplate(template)">Edit</button>
                            <button class="btn brand-button-fail btn-outline" ng-click="deleteTemplate(template)">Delete</button>
                        </div>
                        <hr class="underline"/>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>